package org.mhzd;

import org.mhzd.bytecode.model.Instruction;
import org.mhzd.bytecode.service.*;
import org.mhzd.bytecode.service.Compiler;
import org.mhzd.execution.service.Execute;
import org.mhzd.execution.service.ExecuteImpl;

import java.util.List;

public class Interpreter {
    public static void main(String[] args) {
        System.out.println("Interpreter Project started");

        // Sample program
        List<String> program = List.of(
                "PRINT 1",
                "IF 1",
                "PRINT 2",
                "ENDIF",
                "LOOP 3",
                "PRINT 5",
                "ENDLOOP",
                "PRINT 10"
        );

        System.out.println("=== Source Code ===");
        program.forEach(System.out::println);

        Compiler compiler = new CompilerImpl();
        List<Instruction> instructions = compiler.compileToByteCode(program);

        System.out.println("\n=== Generated Bytecode ===");
        for (int i = 0; i < instructions.size(); i++) {
            System.out.println(i + ": " + instructions.get(i));
        }

        Execute execute = new ExecuteImpl();

        System.out.println("\n=== Execution Output ===");
        execute.execute(instructions);
    }
}